repository:
  name: Backend
  description: Backend API for Sudokuru
  private: false
  delete_branch_on_merge: true
  has_wiki: false
  has_projects: false
  has_downloads: false
  allow_squash_merge: false
  allow_merge_commit: true
  allow_rebase_merge: true
  enable_vulnerability_alerts: true
  enable_automated_security_fixes: true
  
branches:
  - name: master
    protection:
      required_pull_request_reviews: null
      required_status_checks: null
      restrictions: null
      enforce_admins: true
      required_linear_history: true
      allow_force_pushes: false
