
repository:
  has_wiki: false
  has_projects: false
  has_downloads: false
  allow_squash_merge: false
  allow_merge_commit: true
  allow_rebase_merge: true
  enable_vulnerability_alerts: true
  enable_automated_security_fixes: true
branches:
  - name: master
    protection:
      required_pull_request_reviews: null
      required_status_checks: null
      restrictions: null
      enforce_admins: true
